name: Simple HTML CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List project files
      run: ls -R   # Just lists all files to confirm the workflow runs
